package com.redhat.syseng.businessautomation.cep.test

import io.cloudevents.CloudEvent
import com.redhat.syseng.businessautomation.cep.model.Result

declare CloudEvent
  @role( event )
end

//rule eventSeen // this will fire for every insertion
//  when
//   CloudEvent() from entry-point "sample-service"
//  then
//   System.out.println("single event present in working memory");
//  end

//rule multipleEventsSeen // once you put 2 or more events in, this will fire twice - once for each combination
//  when
//   $ce1 : CloudEvent() from entry-point "sample-service"
//   CloudEvent( this != $ce1 ) from entry-point "sample-service"
//  then
//   System.out.println("multiple events present in working memory");
//  end

// another way to detect multiple events, using sliding window instead of the comparison rule above
// note that "length" refers to the last N number of event instances rather than considering their "time"
rule detectBetweenTwoAndFiveEvents
  when
    $numberOfEvents : Number (intValue > 1) from accumulate(
            CloudEvent() over window:length(5) from entry-point "sample-service", count(1))
  then
    System.out.println("sliding detection of 2-5 events present in working memory, current count: " + $numberOfEvents);
  end


// note that since we're firing these so close together, you'll get 2 matches
// see SampleService for a line to uncomment and force the clock ahead > 5 seconds so that the rule won't trigger
rule detectTwoEventsWithinFiveSeconds
  when
    $c1 : CloudEvent() from entry-point "sample-service"
    CloudEvent(this != $c1, this meets[5s] $c1) from entry-point "sample-service"
    // IIRC, the equality check is redundant given the use of a temporal operator, but makes things easier to read
  then
   System.out.println("Some event started within 5 seconds of a different event duration ending");
  end

//rule R1
//  when
//    $r : Result()
//    $e : CloudEvent()
//    Number(intValue > 2) from accumulate($c: CloudEvent(this != $e, this meets[5s] $e) from entry-point "sample-service", count($c))
//  then
//    System.out.println("We have two events 5 seconds apart");
//    $r.setValue("e2 was at least 5s after e1");
//end
